export const USER__AUTH_SET_LOGGED_IN = 'USER__AUTH_SET_LOGGED_IN';
export const USER__AUTH_SET_LOGGED_OUT = 'USER__AUTH_SET_LOGGED_OUT';

export const USER__LOGIN_BY_OPENID = 'USER__LOGIN_BY_OPENID';

export const USER__FETCH_INFO = 'USER__FETCH_INFO';
